"""add: collection and embeddings tables

Revision ID: ab5f802abf92
Revises: 6a37a7866450
Create Date: 2025-12-04 13:53:29.192276

"""

from typing import Sequence, Union
from pgvector.sqlalchemy.vector import VECTOR
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab5f802abf92"
down_revision: Union[str, Sequence[str], None] = "6a37a7866450"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_collection_id"), "collection", ["id"], unique=False)
    op.create_table(
        "document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_id"), "document", ["id"], unique=False)
    op.create_table(
        "collection_document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_document_id"), "collection_document", ["id"], unique=False
    )
    op.create_table(
        "chunk_embedding",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_document_id", sa.UUID(), nullable=False),
        sa.Column("embedding", VECTOR(dim=4096), nullable=False),
        sa.Column("chunk", sa.Text(), nullable=False),
        sa.Column("chunk_metadata", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_document_id"],
            ["collection_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chunk_embedding_id"), "chunk_embedding", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunk_embedding_id"), table_name="chunk_embedding")
    op.drop_table("chunk_embedding")
    op.drop_index(op.f("ix_collection_document_id"), table_name="collection_document")
    op.drop_table("collection_document")
    op.drop_index(op.f("ix_document_id"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_collection_id"), table_name="collection")
    op.drop_table("collection")
    # ### end Alembic commands ###
